CREATE TABLE IF NOT EXISTS Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('admin', 'operator') DEFAULT 'operator',
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS MotoTaxis (
    id INT AUTO_INCREMENT PRIMARY KEY,
    numeroUnidad VARCHAR(50) NOT NULL UNIQUE,
    placas VARCHAR(50) NOT NULL UNIQUE,
    modelo VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Rutas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL UNIQUE,
    origen VARCHAR(255) NOT NULL,
    destino VARCHAR(255) NOT NULL,
    tarifa DECIMAL(10,2) DEFAULT 15.00,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Bitacoras (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tipo ENUM('ENTRADA', 'SALIDA') NOT NULL,
    fechaHora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    userId INT,
    motoTaxiId INT,
    FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE SET NULL,
    FOREIGN KEY (motoTaxiId) REFERENCES MotoTaxis(id) ON DELETE SET NULL
);

-- Insertar un Administrador por defecto para que el profesor pueda iniciar sesión de inmediato
INSERT INTO Users (email, password, role) 
VALUES ('admin@base.com', '123456', 'admin')
ON DUPLICATE KEY UPDATE email=email;